version: "3"
services:

  redis:
    container_name: redis-db
    image: redis:alpine
    volumes:
      - ./redis.conf:/usr/local/etc/redis/redis.conf
    ports:
      - "6379"
    networks:
      - frontend
    deploy:
      replicas: 2
      update_config:
        parallelism: 2
        delay: 10s
      restart_policy:
        condition: on-failure
        
  db:
    container_name: postgres-db
    image: postgres:9.5
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - backend
    environment:
      - POSTGRES_PASSWORD=sample
      - POSTGRES_USER=sample
      - POSTGRES_DB=sample
      - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
      - 5432:5432
          
  web-app:
    build: .
    ports: 
      - 8081:8081
    depends_on:
      - redis
      - db
    deploy:
      replicas: 2
      update_config:
        parallelism: 2
        delay: 10s
      restart_policy:
        condition: on-failure
          
networks:
  frontend:
  backend:

volumes:
  db-data: