server:
  port: 8081
  contextPath: /falcon-message-service
  
spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://db_postgres:5432/sample
    username: sample
    password: sample
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  redis:
    host: db_redis
    port: 6379
